steps:

  #
  # License audit
  #
  - label: 'Electron tests - macOS - Node 14'
    timeout_in_minutes: 40
    agents:
      queue: macos-12-arm
    env:
      DEVELOPER_DIR: "/Applications/Xcode14.app"
      ELECTRON_VERSION: "^20.0.0"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      START_LOCAL_NPM: 1
      VERBOSE: 1
    commands:
      - npm install electron@^20.0.0 --no-audit --progress=false --no-save
      - npm ci --no-audit --progress=false
      - npx lerna bootstrap
      - npm run build:electron
      - defaults write com.apple.CrashReporter DialogType none
      - npm run test:unit:electron-runner
      - npm run test:electron
