steps:

  #
  # Android builder base - used by React Native and React Native CLI
  #
  - label: ":docker: Build Android Builder base image"
    key: "android-builder-base"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v4.12.0:
          build: android-builder-base
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:  android-builder-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base
      - docker-compose#v4.12.0:
          push: android-builder-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Publish/package notifier
  #
  - label: ":docker: Prepare package.json"
    key: "package-js"
    timeout_in_minutes: 3
    plugins:
      - docker-compose#v4.12.0:
          run: minimal-packager
    artifact_paths: min_packages.tar

  - label: ":docker: Build and publish JS packages"
    key: "publish-js"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v4.12.0:
          build: publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ":large_blue_circle: :large_blue_circle: :large_blue_circle: REACT NATIVE (ANDROID) STEPS :large_blue_circle: :large_blue_circle: :large_blue_circle:"
    depends_on:
      - "publish-js"
      - "android-builder-base"
    commands:
      - buildkite-agent pipeline upload .buildkite/basic/react-native-android-pipeline.yml

  - label: ":large_blue_circle: :large_blue_circle: :large_blue_circle: REACT NATIVE (IOS) STEPS :large_blue_circle: :large_blue_circle: :large_blue_circle:"
    depends_on:
      - "publish-js"
    commands:
      - buildkite-agent pipeline upload .buildkite/basic/react-native-ios-pipeline.yml

  #
  # Conditionally trigger full pipeline
  #
  - label: 'Conditionally trigger full set of tests'
    timeout_in_minutes: 30
    command: sh -c .buildkite/pipeline_trigger.sh
