steps:

  - label: ":ios: Build RN 0.72 (Old Arch) ipa"
    key: "rn-0-72-old-arch-ipa"
    timeout_in_minutes: 5
    agents:
      queue: "ms-arm-12-1"
    commands:
      - gem environment
      - ruby --version
    retry:
      manual:
        permit_on_passed: true

  - label: ":ios: Build RN 0.72 (Old Arch) ipa"
    key: "rn-0-72-old-arch-ipa"
    timeout_in_minutes: 60
    agents:
      queue: "ms-arm-12-1"
    env:
      REACT_NATIVE_VERSION: "rn0.72"
      NOTIFIER_VERSION: "7.22.5-ci-tms-mac-build-publish.321c48847c"
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode14.app"
      RCT_NEW_ARCH_ENABLED: "0"
      ARTEFACT_NAME: "rn0.72-old-arch"
    artifact_paths: build/rn0.72-old-arch.ipa
    commands:
      - gem environment
      - ruby --version
      - bundle install
      - npm run test:build-react-native-ios
    retry:
      manual:
        permit_on_passed: true
