steps:

  - label: ":docker: Build and publish JS packages"
    key: "publish-js"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v4.12.0:
          build: publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ":ios: Build RN 0.68 Hermes ipa 6"
    depends_on:
      - "publish-js"
    timeout_in_minutes: 60
    agents:
      queue: ms-arm-12-6
    env:
      REACT_NATIVE_VERSION: rn0.68-hermes
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode13.app"
    artifact_paths: build/rn0.68-hermes.ipa
    commands:
      - npm run test:build-react-native-ios
    retry:
      automatic:
        - exit_status: "*"
          limit: 1
      manual:
        permit_on_passed: true

  - label: ":ios: Build RN 0.68 Hermes ipa 7"
    depends_on:
      - "publish-js"
    timeout_in_minutes: 60
    agents:
      queue: ms-arm-12-7
    env:
      REACT_NATIVE_VERSION: rn0.68-hermes
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode13.app"
    artifact_paths: build/rn0.68-hermes.ipa
    commands:
      - npm run test:build-react-native-ios
    retry:
      automatic:
        - exit_status: "*"
          limit: 1
      manual:
        permit_on_passed: true
