steps:
  - label: ":aws-lambda: AWS Lambda tests"
    timeout_in_minutes: 35
    agents:
      queue: "opensource-mac-cocoa-10.15"
    commands:
      # force the NPM registry as the default on CI is artifactory, which can't
      # currently install from our lockfile
      - npm ci --registry https://registry.npmjs.org
      - cd test/aws-lambda
      - bundle install
      - DEBUG=1 bundle exec maze-runner --tags @serverless-express-app
