steps:
  - label: "Trigger builds"
    plugins:
      - monorepo-diff#v1.0.1:
        diff: "git diff --name-only"
        watch:
        # Any changes to any JS should trigger basic tests
          - path:
              - "packages/**/*"
            config:
              command: "buildkite-agent pipeline upload .buildkite/base.yml"
        # Any changes to appropriate packages or appropriate tests should trigger RN
          - path:
              - "packages/core/**/*"
              - "packages/react-native/**/*"
              - "test/react-native/**/*"
              # ETC
            config:
              command: "buildkite-agent pipeline upload .buildkite/basic/b_1.yml"
        # Any changes to appropriate packages or appropriate tests should trigger Node
          - path:
              - "packages/core/**/*"
              - "packages/node/**/*"
              - "test/node/**/*"
              # ETC
            config:
              command: "buildkite-agent pipeline upload .buildkite/basic/b_2.yml"
        # Any changes to appropriate packages or appropriate tests should trigger browser
          - path:
              - "packages/core/**/*"
              - "packages/browser/**/*"
              - "test/browser/**/*"
              # ETC
            config:
              command: "buildkite-agent pipeline upload .buildkite/basic/b_3.yml"