steps:

  #
  # License audit
  #
  - label: "Ruby checks"
    timeout_in_minutes: 20
    agents:
      queue: ms-arm-12-2
    commands:
      - "echo '***' && gem list"
      - "echo '***' && bundle install"
      - "echo '***' && gem list"
      - "echo '***' && pod --version"
      - "echo '***' && echo $$PATH"
    retry:
      manual:
        permit_on_passed: true


  - label: "Script"
    timeout_in_minutes: 20
    agents:
      queue: ms-arm-12-2
    commands:
      - "pod --version"
      - ./scripts/pod.sh
    retry:
      manual:
        permit_on_passed: true

  - label: "Script"
    timeout_in_minutes: 20
    agents:
      queue: ms-arm-12-2
    commands:
      - "node -e 'require(\"./scripts/react-native-helper\").buildIOS()'"
    retry:
      manual:
        permit_on_passed: true
