steps:

  #
  # Publish/package notifier
  #
  - label: ":docker: Prepare package.json"
    key: "package-js"
    timeout_in_minutes: 3
    plugins:
      - docker-compose#v4.12.0:
          run: minimal-packager
    artifact_paths: min_packages.tar

  #
  # Core tests and checks
  #
  - label: ":docker: Build CI image"
    key: "ci-image"
    depends_on: "package-js"
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.5.0:
          download: min_packages.tar
      - docker-compose#v4.12.0:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base-${BRANCH_NAME}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base
      - docker-compose#v4.12.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base-${BRANCH_NAME}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base
    env: 
      BUILDKITE_STRICT_SINGLE_HOOKS: "true"

  # React Native
  - label: ":large_blue_circle: :large_blue_circle: :large_blue_circle: REACT NATIVE (ANDROID) STEPS :large_blue_circle: :large_blue_circle: :large_blue_circle:"
    depends_on:
      - "publish-js"
      - "android-builder-base"
    commands:
      - buildkite-agent pipeline upload .buildkite/basic/react-native-android-pipeline.yml

  - label: ":large_blue_circle: :large_blue_circle: :large_blue_circle: REACT NATIVE (IOS) STEPS :large_blue_circle: :large_blue_circle: :large_blue_circle:"
    depends_on:
      - "publish-js"
    commands:
      - buildkite-agent pipeline upload .buildkite/basic/react-native-ios-pipeline.yml
