steps:

  - label: ":docker: Build and publish JS packages"
    key: "publish-js"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.9.0:
          build: publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js

  - label: ":large_blue_circle: :large_blue_circle: :large_blue_circle: ELECTRON STEPS :large_blue_circle: :large_blue_circle: :large_blue_circle:"
    commands:
      - buildkite-agent pipeline upload .buildkite/electron-pipeline.yml
    depends_on: "publish-js"

