steps:

  #
  # License audit
  #
  - label: "Ruby checks"
    timeout_in_minutes: 20
    agents:
      queue: ms-arm-12-2
    commands:
      - echo "***" && gem list
      - echo "***" && "bundle install"
      - echo "***" && gem list
      - echo "***" && "pod -v"
      - echo "***" && "echo $$PATH"
    retry:
      manual:
        permit_on_passed: true
