name: AWS Lambda test run

on: [push, pull_request]

jobs:
  aws-lambda:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '^20.0.0'

    - name: Install libcurl4-openssl-dev and net-tools
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev net-tools

    - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - run: cd test/aws-lambda && bundle install && bundle exec maze-runner
