name: Test

on: push

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        electron: [ '^11.2.0' ]
        node-version: [12, 14]
        os: [ ubuntu-20.04, windows-2019, macos-10.15 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v2
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install electron@${{ matrix.electron }} --no-audit --progress=false --no-save
    - run: npm ci --no-audit --progress=false
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - run: npx lerna bootstrap
    - run: npm run test:lint
    - run: npm run test:unit
      env:
        ELECTRON_DISABLE_SANDBOX: 1
    - name: (macOS) disable crash dialog
      if: contains(matrix.os, 'macos')
      run: defaults write com.apple.CrashReporter DialogType none
    - name: run integration tests
      run: npm run test:cucumber
      env:
        START_LOCAL_NPM: 1
        VERBOSE: 1
        ELECTRON_VERSION: ${{ matrix.electron }}
