name: Test

on: push

jobs:
  test:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npx lerna bootstrap
    - run: npm run test:lint
    - run: npm run test:unit
